import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MergedProvider from "@/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SilverLink - Experience Never Retires.",
  description: "Generated by create next app",
};

/**
 * Application root layout that wraps page content with global providers and base HTML structure.
 *
 * Renders an HTML document root (lang="en") with the configured Geist fonts applied to the body and the children mounted inside the document body, all wrapped by the MergedProvider.
 *
 * @param children - The page content to render inside the root layout
 * @returns A JSX element representing the application's root layout
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <MergedProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
        </body>
      </html>
    </MergedProvider>
  );
}